### ISSUE TITLE
plugComponentContext not working ?

### ISSUE THREAD

**Issue by Spy-Seth** [yahoo/fluxible#123]
hey,

I'm using fluxible 0.3.3 and I'm trying to build a simple plugin to manage the localisation: https://gist.github.com/Spy-Seth/6cf7f35133ca93ce9c09

Nothing complicated here. I want to add a method `getLocale` on the context to use it in my component.

But with this code, I haven't the method `getLocale` in my context (`this.context` in my component), I only have it if I do: 

```js
var context = app.createContext();
var componentContext = context.getComponentContext();

var locale = componentContext.getLocale() // works
```

Did I have misunderstood the documentation ?

**Comment by Ambroos** [comment]
It's a bit unclear in the documentation, I had the same issue a few weeks back and solved it after a few hours of digging through the source and tweeting around.

When you use things from context in a React component, you have to declare it in the contextTypes.

What you'd do here:

```javascript
var MyComponent = React.createClass({
    contextTypes: {
        router: React.PropTypes.func, // react-router
        executeAction: React.PropTypes.func, // Fluxible without mixin
        getLocale: React.PropTypes.func // your plugin
    }
    // ...
}
```
There are a few caveats. If you use the FluxibleComponent wrapper, you'll have to modify it to add your plugin functions to the `childContextTypes`. However, I recommend you switch to the new [provideContext](https://github.com/yahoo/fluxible/blob/master/docs/api/addons/provideContext.md). With `provideContext`, it works like this:

```javascript
class Application extends React.Component {
    render() {
        // Stuff and things
    }
}
Application = provideContext(Application, { //jshint ignore:line
    getLocale: React.PropTypes.func.isRequired
});

export default Application;
```

So, there's two steps to it.

1. Provide the context with the extra plugged methods through `provideContext` with additional `contextTypes`. (Or, alternatively, with FluxibleComponent, but I'd just switch.)
2. Declare that you need this context function to be available in every component you need it in with `contextTypes`.

It feels a bit like dependency injection if you ask me, but once you get the hang of it it makes sense. Avoid using mixins for these things. It seems tempting at first, but we seem to be moving away from them, and since Fluxible v0.4 you can do everything without em.
