### ISSUE TITLE
react-router is not getting access to context

### ISSUE THREAD

**Issue by jimzhan** [yahoo/fluxible#170]
**app.js**
```javascript
function RenderApp() {
  const flux = new Fluxible({ component: Routes });
  var context = flux.createContext();

  Router.run(flux.getComponent(), HistoryLocation, function(Handler) {
    React.render(<Handler context={context.getComponentContext()}/>, document.body);
  });
}
```

**Routes.jsx**
```javascript
export default (
  <Route name="app" handler={App} path="/">
    <Route name="about" handler={About} />
    <DefaultRoute name="home" handler={Home} />
  </Route>
);
```

**App.jsx**
```javascript
export default class App extends Component {
  render() {
    return (
      <div id="app">
        <Header />
        <main>
          <div className="container">
            <RouteHandler />
          </div>
        </main>
        <Footer />
      </div>
    );
  }
}
```

**Header.jsx**
```javascript
export class Header extends React.Component {
  static contextTypes = {
    executeAction: PropTypes.func.isRequired
  }

  authorize() {
    this.executeAction(actions.authorize);
  }

  render() {
    return (
      <header className="navbar-fixed">
        <nav className="light-blue darken-4">
          <div className="nav-wrapper container">
            <a href="#!" className="brand-logo">Logo</a>
            <a href="#" data-activates="mobile-demo" className="button-collapse">
              <i className="mdi-navigation-menu"></i>
            </a>
            <ul className="right hide-on-med-and-down">
              <li><a href="#" onClick={this.authorize}><i className="fa fa-github fa-2x"></i></a></li>
              <li><Link to="home">Home</Link></li>
              <li><Link to="about">About</Link></li>
            </ul>
          </div>
        </nav>
      </header>
    );
  }
}
```

**Comment by jimzhan** [comment]
With provideContext(Routes), React failed to render the correct content, neither the FluxibleComponent.

**Comment by mridgway** [comment]
It should work with `FluxibleComponent`:

```js
Router.run(flux.getComponent(), HistoryLocation, function(Handler) {
  React.render(<FluxibleComponent context={context.getComponentContext()}><Handler/></FluxibleComponent>, document.body);
});
```

You can see this in our example here https://github.com/yahoo/flux-examples/blob/master/react-router/client.js#L26

**Comment by jimzhan** [comment]
@mridgway tried & failed either, same error:

```javascript
Uncaught TypeError: Cannot read property 'executeAction' of undefined
```

Seem the context is not being propagated at all.

**Comment by mridgway** [comment]
Make sure you don't have multiple React versions installed, for instance if you're using npm link. Otherwise I'm not sure.

**Comment by jimzhan** [comment]
@mridgway nope, just the latest one (version: 0.13.3).

**Comment by kaivi** [comment]
I seem to have a similar problem with context not propagating down. Here is where I've seen context.executeAction last time:
![screen shot 2015-05-26 at 00 09 35](https://cloud.githubusercontent.com/assets/3091192/7802708/ee11568e-033b-11e5-943d-18d76b44ed6e.png)
I've used Yeoman generator from fluxible.io, and something looks horribly wrong here.

**Comment by mridgway** [comment]
@kaivi It looks like you're using both `provideContext` and `FluxibleComponent`. You should only need to use one or the other. This may be an ordering issue as well. If you're using `provideContext`, it should be the last thing that you call on your app component so that is at the very top level.

**Comment by kaivi** [comment]
@mridgway I've figured it out after googling a bit. My problem was incorrect class setup in ES6 (*wrong both syntactically and not according to the Fluxible guide*), that's why my component did not receive any context. I did it right and it worked, but I ended up wrapping the component in a `provideContext()` instead, which did magic.

One other thing is strage, together with `Unknown` components in React inspector, is that I can not find any references to FluxibleComponent in my source dir, it only shows up in webpacked file. I have just generated a new project with Yeoman, and the React layout is exactly the same as in previous picture. I'm on Node v0.12.4.

Also the Yeoman-generated app (*gulp option*) prints `[Object object]` into console on each request, and fails with HTTP 500 on /favicon request. Also the page titles are all empty, and `Nav.selected` is set to `null`. Is this maybe an issue a new thread?

**Comment by cesarandreu** [comment]
[This issue](https://github.com/rackt/react-router/issues/1093#issuecomment-105329622) might be related, I'm having the same issue.

**Comment by mridgway** [comment]
`FluxibleComponent` may be included in your webpacked file if you `require('fluxible/addons')` or `import ... from 'fluxible/addons'` even if it is not used.

We will take a look at the gulp output.

**Comment by d-adamkiewicz** [comment]
Freshly installed fluxible (WinXP box), created an app, run it (grunt). When url http://localhost:3000 opened in Chrome it produces on console:

Error: Url does not exist
    at module.exports (C:\cygwin\home\some_user\fluxible\node_modules\fluxible-router\lib\navigateAction.js:29:27)
    at executeActionInternal (C:\cygwin\home\some_user\fluxible\node_modules\fluxible\lib\FluxibleContext.js:166:18)
    at Immediate._onImmediate (C:\cygwin\home\some_user\fluxible\node_modules\fluxible\lib\FluxibleContext.js:133:17)
    at processImmediate [as _immediateCallback] (timers.js:358:17)

The messages are repeated "on refresh" in Chrome, but not in Firefox.

**Comment by mridgway** [comment]
@d-adamkiewicz Can you try updating your `generator-fluxible` version (globally). We released a version earlier today that should have addressed this. I just ran the grunt generator locally (on Windows 8) with no issues.

If you have further trouble with it, please open a new issue since this is likely a different issue.

**Comment by d-adamkiewicz** [comment]
@mridgway It worked! Thanks

**Comment by cesarandreu** [comment]
I was having an issue with server-side rendering, I'm compiling the server with webpack and it would fail to get the correct context. Based on some comments in the issue I linked above, I figured out it was because I was loading react twice. 

I fixed it by updating my externals generator like this:

```js
    config.externals.push(
      fs.readdirSync('node_modules')
        .filter(function (x) {
          return ['.bin', 'react'].indexOf(x) === -1
        })
        .reduce(function (nodeModules, mod) {
          nodeModules[mod] = 'commonjs ' + mod
          return nodeModules
        }, {
          'react/addons': 'commonjs react/addons',
          'react': 'commonjs react/addons'
        })
    )
```

It turned out Fluxible was not the problem.

**Comment by jimzhan** [comment]
For anyone still curious about this issue, I've finally figured it out.

This is the Why: [React Autobinding](http://facebook.github.io/react/blog/2015/01/27/react-v0.13.0-beta-1.html#autobinding)
