### ISSUE TITLE
Unable to use Bluebird's global error listeners

### ISSUE THREAD

**Issue by eliseumds** [yahoo/fluxible#186]
I would like to capture uncaught exceptions using [Bluebird's error handlers](https://github.com/petkaantonov/bluebird/blob/master/API.md#user-content-global-rejection-events) but I cannot because of *setImmediate*. How are you guys approaching error handling?

Exception I would like to get:

![screen shot 2015-06-10 at 14 59 20](https://cloud.githubusercontent.com/assets/640840/8082945/79f51194-0f81-11e5-95c7-7a6ffd77fd3f.png)

Exception I am currently getting:

![screen shot 2015-06-10 at 15 00 00](https://cloud.githubusercontent.com/assets/640840/8082948/7e1e3336-0f81-11e5-81e9-526690f63299.png)

Thanks!

**Comment by cesarandreu** [comment]
When you create a Fluxible instance, you can pass a [componentActionHandler](http://fluxible.io/api/fluxible.html#constructor) function that will get called when there's an error.

Thinking about it a bit... It should probably get renamed to `componentActionErrorHandler`, since it'll only get called when there's an error, and it could probably pass the error object directly instead of wrapping it.

@mridgway thoughts?

**Comment by mridgway** [comment]
Correct, we recommend using `componentActionHandler`. I agree with the naming. I will change it for 1.0 release.
