### ISSUE TITLE
Cannot read property 'emitChange' of undefined

### ISSUE THREAD

**Issue by kilometers** [yahoo/fluxible#204]
`Uncaught TypeError: Cannot read property 'emitChange' of undefined`

A store calls a custom function `loadPaths` from within the `initialize` function, which in turn runs `this.emitChange()` -- That works fine. However, calling `emitChange` in the `createPath` function throws the above error. I must be missing something. Ideas? I'll be sleeping on it...

```
'use strict';
var createStore = require('fluxible/addons').createStore;
var request = require('request');

var PathStore = createStore({
    storeName: 'PathStore',
    handlers: {
        'LOAD_PATHS': 'loadPaths',
    },
    initialize: function () {
        this.paths = new Map();
        this.loadPaths();
    },
    loadPaths: function () {
        request('http://localhost:3000/api/paths', function(err, res, body) {
            err = res;
            var paths = JSON.parse(body);
            for(var i = 0; i < paths.length; i++){
                this.paths.set(paths[i]._id, paths[i]);
            }
            this.emitChange();
        }.bind(this));
    },
    getPaths: function () {
        return this.paths;
    },
    createPath: function () {
        request.post('http://localhost:3000/api/paths', {}, function(err, res, body) {
            this.emitChange();
        }.bind(this));
    },
    dehydrate: function () {
        return {
            paths: this.paths
        };
    },
    rehydrate: function (state) {
        this.paths = state.paths;
    }
});

module.exports = PathStore;
```

**Comment by cesarandreu** [comment]
Is createPath being called with the right context? Is request overriding it?

**Comment by kilometers** [comment]
In the `createPath` function, `this` is still undefined outside of request, so I don't think request is the culprit. How might I test for the correct context?

**Comment by cesarandreu** [comment]
I'd just set the debugger and check the `this` value, but it sounds like you already did that...

Your bug is likely caused by the way you're calling `PathStore.createPath`, since the context is undefined. How are you calling createPath?

**Comment by kilometers** [comment]
Ahhh. That was the problem.

I cut a corner, like so:
```
     <button onClick={this.getStore(PathStore).createPath}>New Path</button>
```

However, this blasted the context. Fixed:
```
    render: function () {
        return (
            <button onClick={this.createPath}>New Path</button>
        );
    },
    createPath: function () {
        this.getStore(PathStore).createPath();
    }
```

I'll be sure to avoid the former pattern (it was messy anyway), however *why* it changed the context isn't clear to me. I wouldn't mind a short explanation if you have one :)

**Comment by cesarandreu** [comment]
Glad to be of help, and sure I'll try to explain. If my explanation is confusing, check out the [MDN article](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/this) as well. 

Ended up not being that short... But anyway;

`React.createClass` does automatic binding of component functions (methods) for you when it creates the component instance, that's what makes it so that when you pass a function to, for example, onClick, it'll have the correct `this` (context). They do this for you because it's convenient, otherwise you would need to bind functions yourself, e.g. `onClick={this.createPath.bind(this)}` (which you have to do when you use `React.Component`).

If you're in strict mode, the value of `this` when a function is invoked is always going to be whatever is on the left hand side of the function at the time it is called. The only exception to this are when you use `bind`, `call`, or `apply`.

So when you did ` onClick={this.getStore(PathStore).createPath}`, it was only passing along the `createPath` function, but it didn't have a context.

Here's a small example that shows the same type of behavior that you were having in your code:

```js
function Foo (value) {
  this.value = value
}

Foo.prototype.bar = function bar () {
  console.log('Foo.bar, the value is', this.value)
}

const foo = new Foo(true)
foo.bar()
// "Foo.bar, the value is true"

const bar = foo.bar
bar()
// "Foo.bar, the value is undefined"
```

As you can see, when `bar` gets called, it doesn't have a context, the same as when you were calling `createPath`, that's because `bar` is being called and there's nothing on the left. 

I'd suggest opening up Chrome Dev Tools and playing around with it for a bit, I think once you fool around with the behavior and you test different cases it'll become clearer.

**Comment by kilometers** [comment]
I wasn't expecting a small article -- Thanks for the explanation! Context is something I've been happy to use, but not understand. I'll be digging into Dev Tools.
