### ISSUE TITLE
What's the best way to get context inside my plugin?

### ISSUE THREAD

**Issue by x1a0** [yahoo/fluxible#230]
Hi,

I have create a Fluxible plugin called `Api` - it plugs `getApi()` method to `actionContext`. So in my actions I could have something like:

    actionContext.getApi().getUser(uid);

However I don't want to have a callback function here. So action just triggers the Api call and done with its job. Api will broadcast when that request is done, so inside Api there would be something like:

    getUser(uid) {
        asyncHttpGetFuture.then((res) => {
            ...
            context.dispatch('API_USER_LOADED', res);
        }
    }

What I can do is always pass `actionContext` from action to Api so the signature of `getUser` method would be `getUser(context, uid)` - same for all the other api calls - which is ugly i think..

As plugin is part of Fluxible app, I am thinking is there a way that the plugin can get context instance somehow.

However from the document it looks like a plugin itself knows nothing about the Fluxible app it hooks to (which make sense I would say...).

**Comment by cesarandreu** [comment]
Since you're using promises, you can return it from your action creator.

The actionContext that you plug is the same context passed to action creators... So in your plugin you could create a [curried function](https://lodash.com/docs#curry), passing context first and other args on the second call.

I have a plugin that adds `ActionContext#executeRequest(requestCreator: RequestCreator, payload: any)`. The RequestCreator interface is `function RequestCreator (fetch: GlobalFetch.fetch, payload: any): Promise<Response> { ... }`. I pass a browser version (whatwg-fetch) or a node version (node-fetch) depending on the environment. In the server it'll add the cookies to the request and append the protocol + host to the URL. In the browser it'll set the CSRF token. 

Maybe I should publish it, if it'd be useful.

**Comment by mridgway** [comment]
The `plugContext` method actually receives more parameters than we documented (we should fix that): https://github.com/yahoo/fluxible/blob/master/lib/FluxibleContext.js#L214

So the second parameter is the `FluxibleContext` instance and the third is the `Fluxible` instance.

Not sure if that helps your situation.

**Comment by redonkulus** [comment]
Fixed here https://github.com/yahoo/fluxible/commit/4e48b0fa4f2bc6a7f55c76cd9ebe79e350db76df

**Comment by x1a0** [comment]
@mridgway @redonkulus Thank you. That info is helpful. However it results in a circling situation as the plugin has a reference to context instance while context instance also holds a reference to the plugin - not very good I guess.

@cesarandreu Thank you. I think just returning a promise back to actions and let actions dispatch events is good :)
