### ISSUE TITLE
Canceling a router action

### ISSUE THREAD

**Issue by gpbl** [yahoo/fluxible#26]
I'm very happy I've spent some time with fluxible, I'm liking it a lot :+1:

I have a last problem (i hope). This route is fetching some data before calling the `done` callback:

```js
// routes.js
var getBooks = require('../actions/getBooks');
var routes = {
  books: {
    path: '/books',
    page: 'books',
    action: function(context, payload, done) {
       // fetch the books from a REST API
       context.executeAction(getBooks, {}, done);
    }
  }
}
```

When the user visits another route *before the call ends* (e.g. clicking a NavLink), he will jump back to the this route as soon as the "old" action is finished. 

How could I prevent this behaviour? Or is the action expected to be async?

**Comment by mridgway** [comment]
There's not really a way to cancel the execution of the first page that was clicked since it's async. Your store that handles page state would have to keep track of the `CHANGE_ROUTE_START` and `CHANGE_ROUTE_SUCCESS` and make sure the page sent to success is the same as the one that was sent from the start event. If they do not match, you wouldn't update the state of the store and then you wouldn't get the redirect that you were seeing.

**Comment by gpbl** [comment]
Thanks, I'll follow that way then.
