### ISSUE TITLE
Improve "require('fluxible-app/utils/createStore')" and also "BaseStore"?

### ISSUE THREAD

**Issue by protron** [yahoo/fluxible#28]
I suggest to improve the way the user has to import the "**createStore**" and "**BaseStore**" utilities. Because the current approach seems like we are requiring a "private" file instead of something well documented and ready for use.

I could provide a PR (if you want). My approach would be just updating the ["Helper Utilities" section in the README.md](https://github.com/yahoo/fluxible#helper-utilities) and the [/index.js](https://github.com/yahoo/fluxible/blob/v0.1.5/index.js) to add the following:

    module.exports.createStore = require('./utils/createStore');
    module.exports.BaseStore = require('./utils/BaseStore');

**Comment by mridgway** [comment]
We don't export these utilities in the index.js because it is not required to use these libraries. If we export it in the index.js, then anyone using webpack or browserify would get them bundled with their application even if they didn't use them. 

We're considering moving these two utilities to a separate package.

**Comment by jedireza** [comment]
:+1: for moving

**Comment by protron** [comment]
Oh, I see. I didn't know that about the bundled. Thank you!

**Comment by redonkulus** [comment]
We have a similar issue in [dispatchr](https://github.com/yahoo/dispatchr/issues/36) to track this.
