### ISSUE TITLE
`this.context` in generator

### ISSUE THREAD

**Issue by tom76kimo** [yahoo/fluxible#286]
https://github.com/yahoo/fluxible/blob/master/packages/generator-fluxible/app/index.js#L44

Is `this.context` a valid parameter in yeoman generator? It seems to be always `undefined`. Maybe can just remove them?

**Comment by mridgway** [comment]
We were previously using this for providing the option of gulp vs grunt, but have since removed them in favor of just using webpack-dev-server. You're right we could probably remove them, but at the same time if we want to provide options in the future we'd have to re-add them anyway. It shouldn't hurt to keep them around.

**Comment by tom76kimo** [comment]
I see, thanks for your answering. :+1:
