### ISSUE TITLE
Safari performance issue

### ISSUE THREAD

**Issue by aishng** [yahoo/fluxible#288]
I've run into a Safari performance issue when building a fluxible app. When a user inputs, deletes, inputs, focuses and/or unfocuses on the input field speedily the app crashes and reloads. 

I'm not entirely sure what is causing this, but passing a value from a store into a prop seems to exacerbate it. I've recreated it here on a smaller dummy app: https://github.com/aishng/yofluxible
If you quickly (and randomly) input, focus, unfocus, and delete the input, you'll see the app crash (in Safari only).

Have you experienced this? Did you find any solutions?

**Comment by mridgway** [comment]
I was able to reproduce the crash using your code in Safari. I'm not sure what could be causing the issue in this case. It might be worth trying to recreate this without Fluxible and see if it could be a React specific issue or something that is caused by Fluxible. I'd be surprised if Fluxible would cause this though.

I will play around some more to see if I can find any solution.

**Comment by mridgway** [comment]
I ran a profile in chrome to see what could be causing issues (I was thinking memory could be an issue). The memory does seem to spike at first but then comes back in control. Curiously the number of DOM nodes seems to increase over time without being cleaned up.

<img width="1051" alt="screen shot 2015-10-20 at 11 49 45 am" src="https://cloud.githubusercontent.com/assets/191142/10617707/ba00a292-7720-11e5-828c-45540780bdac.png">

**Comment by malaman** [comment]
We also have safari crash issue (in our app we call executeAction on onMouseLeave and onMouseEnter methods of  React component). For us it appears only in node DEVELOPMENT mode. In PRODUCTION mode we do not experience safari crashes, but slight decline of the performance (comparing to Chrome)

**Comment by mridgway** [comment]
Strange. I'm not longer able to reproduce the crash in safari using the same example above, although it may be due to the node modules being updated as well.

@malaman are you seeing this with the above example or only within your own application?

**Comment by malaman** [comment]
I was able to reproduce crash with the example above.
I did some modifications to the example app: https://github.com/malaman/yofluxible.git to show pattern in our application. On my Macbook (El Capitan 10.11.3, Safari 9.0.3) if user quickly moves a mouse up and down to enable onMouseEnter and onMouseLeave methods for the first input application will crash in safari.

**Comment by mridgway** [comment]
If I remove `setImmediate` calls in `executeAction` (`utils/callAction.js`), the crash seems to go away. This is most likely due to too many timers being registered. I'm going to dig in to see which abstraction `setImmediate` is using in safari and see if there's any related issues that others are seeing.

**Comment by mridgway** [comment]
Looks like it's webpack's default `setImmediate` polyfill that is the problem as we saw in https://github.com/yahoo/fluxible/issues/250. Try adding the following lines and see if you still see the issue: https://github.com/yahoo/fluxible/blob/master/packages/generator-fluxible/app/templates/webpack.config.js#L31-L33

**Comment by malaman** [comment]
With <pre>setImmediate: false</pre> crashes are gone from example repo as well as from our app.
Thank you for help!
