### ISSUE TITLE
MockAction for use with MockActionContext

### ISSUE THREAD

**Issue by localnerve** [yahoo/fluxible#294]
Wondering if it is a good idea to add a MockAction (wrapper) for use with MockActionContext to supply Promise fulfillment if 'done' callback is missing, or just update the MockXXXContext utils directly to use a common fulfillment mechanism.

More and more my code is making use of Promises, and I suspect this is growing for everyone.

I rely pretty heavily on the Fluxible Utils, so if these are going to stick around (which I super-hope they do), then they probably should get an update for actions that make use of Promises in one way or another.

Other Ideas?

**Comment by mridgway** [comment]
Yes, they're sticking around and should definitely support Promises. I would prefer updating MockXXXAction as you mentioned above.

**Comment by localnerve** [comment]
Trying to run the tests on this, can't `npm install` in Node 4.2.1. Works in 0.12.x, but I'm guessing.

Please explicitly show in the repo `package.json` what Node range is expected (if only for contribution).

**Comment by mridgway** [comment]
Yeah, jsdom is unfortunately incompatible across Node versions. I want to find a way to get development working across versions. The problem with adding the range in package.json is it will warn when installed in "incompatible" version, but in our case the issue is only with a dev dependency.

We should add a note to the Readme though for sure.
