### ISSUE TITLE
the best way to handle styles in fluxible isomorphic components

### ISSUE THREAD

**Issue by ali1k** [yahoo/fluxible#381]
One part which I see missing in fluxible is handling custom css styles in the component level.
I was wondering how we can handle styles in an isomorphic way in fluxible!?  Can we apply CSS modules (https://github.com/css-modules/css-modules) to isomorphic react components? or are there any libraries from Yahoo to tackle the issue of styling in fluxible?

**Comment by mridgway** [comment]
You should be able us use css-modules with https://github.com/css-modules/css-modules-require-hook, but I haven't tried this out. Internally we use [Atomic CSS](http://acss.io/) which was built in-house for creating extremely small stylesheets.

There are too many options for doing styling in React that are out there for us to make a specific recommendation, since they all solve different problems.

**Comment by ali1k** [comment]
I couldn'r configure the css modules in fluxible and for now decided to stick to React inline styles + https://github.com/JedWatson/classnames which sound a good enough solution. Would be great if you could point out to some fluxible examples where Atomic CSS or other styling approach is implemented. thanks

**Comment by redonkulus** [comment]
Take a look at our docs site for example https://github.com/yahoo/fluxible/tree/master/site
