### ISSUE TITLE
executeAction callback confusion

### ISSUE THREAD

**Issue by icodeforlove** [yahoo/fluxible#426]
When I'm server-side rendering and i fire a `executeAction` the callback fires before the stores can propagate the change to the components that are listening to the stores.

executeAction -> emitChange -> renderToStaticMarkup

Is it wrong to assume that `renderToStaticMarkup` should be rendering the updates the action triggered?

**Comment by mridgway** [comment]
It's not typical to use store listeners on the server-side because the components will not be "mounted" at all. So yes, unless you are emulating the DOM in the server-side (which I don't recommend for performance reasons), you shouldn't be relying on `renderToStaticMarkup` will not use the `change` events for updating. Instead you should get all of the state where you want it before calling `React.renderToStaticMarkup`.

**Comment by icodeforlove** [comment]
I was doing that, apparently running a `superagent` plugin in the action was causing some sort of conflict.

I ended up replacing it with `isomorphic-fetch` and that solved my problems.
