### ISSUE TITLE
Documentation indicates that executeAction callbacks are called when the action is finished, but this doesn't happen

### ISSUE THREAD

**Issue by yourcelf** [yahoo/fluxible#43]
Issue #42 indicates that it is by design that ``executeAction`` does not call its callback; however, the documentation at http://fluxible.io/api/fluxible.html#executeaction-action-payload-callback- indicates that the callback is called.

This is confusing!

**Comment by koulmomo** [comment]
If I recall someone also asked the same thing in the [gitter.im chat room](https://gitter.im/yahoo/fluxible) too.

To clear up your confusion until the docs explain this better

From the [fluxible.io site](http://fluxible.io/guides/plugins.html)

> Within a context, Fluxible creates interfaces providing access to only certain parts of the system. These are broken down as such:

 > * **Action Context**: interface accessible by action creator methods. Passed as first parameter to all action creators.
 > * **Component Context**: interface accessible by React components. Should be passed as prop to top level React component and then propagated to child components that require acess to it.
 > * **Store Context**: interface accessible by stores. Passed as first parameter to all stores. See [Dispatchr docs](https://github.com/yahoo/dispatchr#constructor-1).

So, by design, the context used by `action creators`, `components`, and `stores` are different.

* The `store` context does not provide an `executeAction` method
* The `component` context **does** provide an `executeAction` method but never calls the `done` callback. This forces your components to only rely on `state`, `props`, and `store` changes for determining state (that's what #42 is referencing)
* The `action creator` context provides an `executeAction` method but **does** call the `done` callback. This was a necessary addition since you need a way server side to determine when it was safe to call `render` on your application.

**Comment by redonkulus** [comment]
thanks @koulmomo. Ya the `executeAction` in the docs refers to the actionContext type. Unfortunately, its not clear from the docs. We will clear that up.

**Comment by MrOrz** [comment]
I've also encountered this problem.
I think it would be nice to have in the doc a comparison table that lists all the contexts, (action context, component context, store context, and fluxible context). The table compares their designed purposes as well as API, like there is no `getStore` in FluxibleContext, no `done` in the argument of component context's `executeAction`, and so on. A table can be helpful in clearifing contexts' design.

**Comment by mridgway** [comment]
:+1: Good idea. I'll add this to the [FluxibleContext doc](https://github.com/yahoo/fluxible/blob/master/docs/api/FluxibleContext.md)

**Comment by mridgway** [comment]
Added here: https://github.com/yahoo/fluxible/blob/master/docs/api/FluxibleContext.md#subcontexts

**Comment by tlovett1** [comment]
Wish this were more clear :)
