### ISSUE TITLE
<FluxibleComponent /> invalid proptype warning

### ISSUE THREAD

**Issue by nim23** [yahoo/fluxible#476]
https://facebook.github.io/react/warnings/unknown-prop.html

With React 15.2.0 and above, proptypes that are not valid throws a warning. I have been using the ```<FluxibleComponent/>``` to pass in context to components inside a modal, because the component is not the child of the ```App``` component.

```javascript
  let html = ReactDOM.renderToString(
    <FluxibleComponent context={context.getComponentContext()}>
        <Component />
    </FluxibleComponent>
);
```

When I upgrade the app to react 15.3.0, my code which looks similar to above example gives me a warning for an ```unknown prop type context in div```.

Does ```fluxible``` have any plan to upgrade and support the latest version of react in the future, and in the meantime are there any alternative solution for the situation above.

Thanks,
Nimesh

**Comment by mridgway** [comment]
There may be people relying on the `context` prop being sent to that application component so we can't remove the propagation outright. The only option would be to check the type of the child to see if it is native or not to determine child props.

I will say though that it seems kind of odd to have a native component underneath `FluxibleComponent`, since it's meant as a wrapper around your application.

**Comment by nim23** [comment]
@mridgway Thanks. Your last paragraph/sentence made much more sense. I had a native element under the `FluxibleComponent`, wrapped it in functional component which seem's to do away with the warning. Found the `FluxibleComponent` very handy for giving providing context to component's in a `Modal` which are not child components of the `App` component. Not really sure now after reading your comment.

Closing the issue for now.
