### ISSUE TITLE
Flow Annotations

### ISSUE THREAD

**Issue by mridgway** [yahoo/fluxible#49]
Flow now allows using comments for annotations which would allow us and our users validate their usage of Fluxible.

http://flowtype.org/blog/2015/02/20/Flow-Comments.html

**Comment by cesarandreu** [comment]
What tooling do people use for this sort of stuff?

I've been considering trying out [flowcheck](http://gcanti.github.io/flowcheck/), since it works with babeljs and it has a webpack loader. 

Do [ternjs](http://ternjs.net/) or [SublimeCodeIntel](http://sublimecodeintel.github.io/SublimeCodeIntel/) work with babeljs?

**Comment by mridgway** [comment]
I think babel/babel-loader actually supports Flow out of the box: http://babeljs.io/docs/advanced/transformers/other/flow/.

I'm not sure how to get support for them in editors, but if we use JS comments for flow then we don't have to worry too much with highlighting invalid syntax.

**Comment by cesarandreu** [comment]
Oh, I use [babel-sublime](https://github.com/babel/babel-sublime) and [babel-eslint](https://github.com/babel/babel-eslint), but I don't think flow types will be checked by babel-eslint (i.e. it won't notify you of incorrect usage), and I don't know if any of the JS intellisense libs work with babel + flow.

I just realized it's probably off topic though, since I sorta assumed everyone is using babel, which is likely NOT the case.

**Comment by redonkulus** [comment]
As TS has taken over in recent years, it would be better to annotate there. Closing this since we will not at Flow ones.
