### ISSUE TITLE
componentWillReceiveProps to getDerivedStateFromProps

### ISSUE THREAD

**Issue by roderickhsiao** [yahoo/fluxible#587]
React 16.3 introduce `getDerivedStateFromProps`. currently we are using in `connectToStores.js` and `createNavLinkComponent.js`.

React already starts throwing warning if client migrate the component to use `getDerivedStateFromProps` while wrapping with `connectToStores` 

![screen shot 2018-04-25 at 6 14 47 am](https://user-images.githubusercontent.com/3906130/39248072-fee78990-484f-11e8-8689-40fd943a43c1.png)

We could use https://github.com/reactjs/react-lifecycles-compat#readme to support old version.

**Comment by redonkulus** [comment]
Using the polyfill is probably the safest bet so that we don't have to bump major version. I will try to get this when I get time or you can provide a PR 😀

**Comment by roderickhsiao** [comment]
the honor is yours :) I will check if I have time as well, I think polyfill should be fine but we probably want to wait the polyfill to be stable as it do have breaking changes for the past two weeks

https://github.com/reactjs/react-lifecycles-compat/blob/master/CHANGELOG.md

**Comment by redonkulus** [comment]
@pablopalacios looks like in the new 1.x release we still have the `UNSAFE_componentWillReceiveProps` prefix in the places mentioned above, from your [analysis](https://github.com/yahoo/fluxible/pull/650) in this change, looks like we cannot use `getDerivedStateFromProps` since its a static and we need access to `this.context` (although maybe this has changed since last year). 

What are your thoughts now that we have a 1.x release and could remove the old UNSAFE_ methods.

**Comment by pablopalacios** [comment]
It might be possible if we convert `connectToStores` to a functional component and use the `useEffect` hook. But I bet that it's still a tricky problem. I might give a try soon and see if it's possible.

**Comment by redonkulus** [comment]
Fixed via https://github.com/yahoo/fluxible/pull/747
