### ISSUE TITLE
Render a component when error occurs

### ISSUE THREAD

**Issue by ccolonna** [yahoo/fluxible#680]
Hi, how can i simply render a ErroHandler component when app throws error in client side. Specifically when hitting a missing route.

I followed classic React documentation:
https://reactjs.org/blog/2017/07/26/error-handling-in-react-16.html

Fluxible app is rendered like this:

```
let app = new Fluxible({
    component: MyApplication,
    ...
})
```

And I wrapped my application with an `ErrorHandler` Component:

```
export default class MyApplication extends React.Component {
    render() { 
        return <ErrorHandler>
                         ... my app tree
                  <ErrorHandler>
    }
}
```

But for example when i ask a missing route (**on the client side**) i get an error like this

```
`TypeError: Cannot read property 'handler' of null`
```

This is not handled by `ErrorHandler`, instead white screen appear with error in the console.

**Comment by pablopalacios** [comment]
I'm pretty sure that it's not rendering the ErrorBoundary because the error you are getting is not a react component error. Probably it happens in action. From React docs:

```
Error boundaries do not catch errors for:

    Event handlers (learn more)
    Asynchronous code (e.g. setTimeout or requestAnimationFrame callbacks)
    Server side rendering
    Errors thrown in the error boundary itself (rather than its children)
```
If the error is happening in action that you don't have control, you can set a global action error handler in your fluxible application when you instantiate it. It is documented here: https://fluxible.io/api/fluxible.html#-code-options-componentactionerrorhandler-code-
