### ISSUE TITLE
Provide props from top level component (FluxibleComponent?)

### ISSUE THREAD

**Issue by joemcbride** [yahoo/fluxible#70]
I'm interested in seeing a top level component that provides props populated from stores to child components.

Example before/after usage.

```
// this is how you work with a store using FluxibleMixin directly
const ProductList = React.createClass({
 
  mixins: [FluxibleMixin],
 
  statics: {
    storeListeners: {
      _onChange: [ProductsStore]
    }
  },
 
  getInitialState() {
    return {
      products: this.getStore(ProductsStore).getProducts()
    }
  },
 
  _onChange() {
    let products = this.getStore(ProductsStore).getProducts();
    this.setState({products: products});
  },
 
  render() {
    let products = this.state.products || [];
    let list = products.map((d, i)=>{
      return (<li key={i}>{d.title}</li>);
    });
    return (
      <div>
        <h2>products</h2>
        <ul>
          {list}
        </ul>
      </div>
    );
  }
});
 
const ProductPage = React.createClass({
  render() {
    return (
      <ProductList/>
    );
  }
});
 
 
// using FluxComponent
// queries: provide a list of store to props mappings, could also provide other meta information
// Component's props auto-update on change
// Now the Components can be interrogated for information
// Ask them questions like:
//   What stores do my children access?
//   Are those stores 'initialized'?
 
const ProductList = React.createClass({
 
  statics: {
    queries: [{
      store: ProductsStore,
      map: store =>({
        products: store.getProducts()
      })
    }]
  },
 
  render() {
    let products = this.props.products || [];
    let list = products.map((d, i)=>{
      return (<li key={i}>{d.title}</li>);
    });
    return (
      <div>
        <h2>products</h2>
        <ul>
          {list}
        </ul>
      </div>
    );
  }
});
 
const ProductPage = React.createClass({
  render() {
    return (
      <FluxComponent>
        <ProductList/>
      </FluxComponent>
    );
  }
});
```

Here is an initial spike of such a component.

```
import React from 'react';
import assign from 'object-assign';
import { FluxibleMixin } from 'fluxible';
 
const FluxComponent = React.createClass({
 
  mixins: [FluxibleMixin],
 
  componentDidMount(){
    this.listeners = [];
 
    React.Children.forEach(this.props.children, child=>{
      child.type.queries.forEach(query=>{
        this._registerListener({
          store: this.getStore(query.store),
          map: query.map,
          handler: this._updateState
        });
      });
    });
 
    this._updateState();
  },
 
  componentWillUnmount() {
    this.listeners.forEach(listener=>{
        listener.store.removeChangeListener(listener.handler);
    });
    this.listeners = [];
  },
 
  _registerListener(listener){
    this.listeners.push(listener);
    listener.store.addChangeListener(listener.handler);
  },
 
  _updateState(){
    var state = this._getStoreState();
    this.setState(state);
  },
 
  _getStoreState(){
    return this.listeners.reduce(
      (result, l) =>{
        return assign(result, l.map(l.store));
      }, {}
    );
  },
 
  getChildProps(){
    return assign(
      {},
      this.state,
      this.getChildContext()
    );
  },
 
  render(){
    return React.addons.cloneWithProps(this.props.children, this.getChildProps());
  }
});
 
export default FluxComponent;
```

**Comment by mridgway** [comment]
I like this approach.  I think there's even value in replacing the way `storeListeners` in the `FluxibleMixin` works right now. There's still boilerplate because you have to specify `getInitialState` and the `onChange`. Being able to just provide a function that returns your store state is more ideal, and I like the idea of making that declarative:

```js
storeListeners: {
    FooStore: store => ({ foo: store.getFoo() })
},
```

Naming of `storeListeners` or `queries` is of course the hard part.

**Comment by mridgway** [comment]
@joemcbride I read through the new [Relay post](http://facebook.github.io/react/blog/2015/03/19/building-the-facebook-news-feed-with-relay.html) and they use a `Relay.createContainer` method to declaratively specify their graphQL queries. What are your thoughts on following a similar pattern for registering metadata about a child component, including the `queries` as in your example. This way we don't have to worry about reaching down into statics of the child either, it's all encapsulated within the container component. This would also allow adding other metadata that could be used in the future for other things (I'm thinking action/fetchr dependencies for instance).

**Comment by joemcbride** [comment]
@mridgway Yes I think that is a perfect idea.  [This post](https://medium.com/@dan_abramov/mixins-are-dead-long-live-higher-order-components-94a0d2f9e750)  gives a good starting point (via @gpbl) .

```
function connectToStores(Component, stores, getStateFromStores) {
  const StoreConnection = React.createClass({
    getInitialState() {
      return getStateFromStores(this.props);
    },
    componentDidMount() {
      stores.forEach(store =>
        store.addChangeListener(this.handleStoresChanged)
      );
    },
    componentWillUnmount() {
      stores.forEach(store =>
        store.removeChangeListener(this.handleStoresChanged)
      );
    },
    handleStoresChanged() {
      if (this.isMounted()) {
        this.setState(getStateFromStores(this.props));
      }
    },
    render() {
      return <Component {...this.props} {...this.state} />;
    }
  });
  return StoreConnection;
};
```

**Comment by gpbl** [comment]
Yeah this is basically what' i'm using now:

```js
import React from 'react';
import { FluxibleMixin } from 'fluxible';

function connectToStores(Component, stores, getStateFromStores, fetchData) {
  const StoreConnection = React.createClass({
    mixins: [FluxibleMixin],

    statics: {
      storeListeners: stores
    },

    getInitialState() {
      return getStateFromStores(this.context, this.props);
    },

    onChange() {
      if (this.isMounted()) {
        this.setState(getStateFromStores(this.context, this.props));
      }
    },

    render() {
      return <Component {...this.props} {...this.state} />;
    }

  });

  return StoreConnection;
}

export default connectToStores;
```

Then in my component:

```js
import connectToStores from './connectToStores';
let MyComponent = React.createClass...
//snip   
   render() { 
    return <p>{this.props.item}</p>;
   }
}

function getStateFromStores(context, props) {
  return {
    item: context.getStore('MyItemStore').get(props.id)
  };
}

MyComponent = connectToStores(MyComponent, ['MyItemStore'], getStateFromStores);
export default MyComponent;

```

**Comment by mridgway** [comment]
:+1: I'm going to add something similar to Dan Abramov's `connectToStores` in 0.4.0.

I'm also considering a similar API to replace the `FluxibleComponent` that would allow custom `childContextTypes`. Will create a separate issue for this.

**Comment by gpbl** [comment]
I've changed my implementation a bit

- Component props should overwrite the props coming from the higher-order component. This would also help testing the component without the stores
- we could also pass `props.context` to the wrapped component, so we can call `this.props.executeAction` without the `FluxibleMixin`:

```js
// connectToStore.js
 render() {
      return <Component {...this.state} {...this.props} context={this.context} />;
    }
```

I'm also thinking to pass the listened stores as argument to `getStateFromStore`. Since it's likely we will use those stores, it would help to skip the `getStore` part:

```js
function getStateFromStores(itemStore, userStore, props) {
  return {
    item: itemStore.get(props.id)
  };
}

MyComponent = connectToStores(MyComponent, ['MyItemStore', 'UserStore'], getStateFromStores);
export default MyComponent;
```

but maybe it complicates the API too much :-)

I've put the whole thing in [this gist](https://gist.github.com/gpbl/8eab887ecbaadb07aead).

A problem raised from this approach is accessing `refs` from the parent component to the wrapped one. I'm not a fan of `refs` (usually you can skip it with a Store), but I'm not yet sure if we should expose it somehow.

**Comment by mridgway** [comment]
> Component props should overwrite the props coming from the higher-order component. This would also help testing the component without the stores

Interesting observation. It seems like state should be higher precedent though to me. I wonder if we should warn if there is overlap between state and props. I can see the point about testing, but it seems like you would want to test with mock stores in place.

> we could also pass props.context to the wrapped component, so we can call this.props.executeAction without the FluxibleMixin

I think this could make it unclear to users whether to use `this.context.executeAction` or `this.props.executeAction`. We are automatically propagating the context for them as long as they specify `contextTypes`.

> I'm also thinking to pass the listened stores as argument to getStateFromStore. Since it's likely we would use those stores, it helps to skip the getStore part

Totally agree on this part. It's pretty much required since the `getStateFromStore` method doesn't have access to the context. I'm playing around with various implementations to find what feels the least verbose.

Something I'm playing with:

```js
let WrappedComponent = connectToStores(Component, [MockStore, MockStore2], {
    MockStore: (store, props) => { foo: store.getFoo(); },
    MockStore2: (store, props) => { bar: store.getBar(); }
});
```

the return values from each store would be merged into one `props` object. Would probably need to warn if there is overlap.

**Comment by gpbl** [comment]
@mridgway I agree with all your observations, thanks for sharing!
