### ISSUE TITLE
best way to combine flux with Websockets

### ISSUE THREAD

**Issue by ali1k** [yahoo/fluxible#85]
I would like to spread changes in stores to all the clients who are watching the affected component. Do you have any suggestions for that? where to add Websockets in Fluxible architecture?

**Comment by mridgway** [comment]
I think having websockets hooked up from a `componentDidMount` on a React component and then have it feed all data through an `executeAction` call. I think this makes the most sense since you don't want to continue the connection if the components that are using the data are no longer on the page.

I haven't actually implemented this yet though.

**Comment by koulmomo** [comment]
we had a similar use case where we needed to set up a polling solution for a component and ended up structuring it in the way @mridgway suggested.

see [`PeriodicActionsMixin`](https://github.com/yahoo/fluxible-action-utils#periodicactions) for more info.

**Comment by ali1k** [comment]
@mridgway thanks for your suggestion. It seems reasonable, I thought maybe there is already a Mixin to support that for fluxible components. Will try @koulmomo solution and will come back to you if I get any trouble!
