### ISSUE TITLE
React 0.14 Observe

### ISSUE THREAD

**Issue by quangv** [yahoo/fluxible#90]
Apparently React 0.14 will have a new life cycle hook `observe`

https://twitter.com/dan_abramov/status/576767008152358912

https://github.com/facebook/react/issues/3398

Do you see any changes for Fluxible / FluxibleMixin in wake of it?

**Comment by mridgway** [comment]
The first change that makes sense is having stores be observable. This would also remove the need for the mixin for store listeners in my opinion, because there's much less boilerplate to listen to stores since it's built-in to React.

The FluxibleMixin is something that we're going to be deprecating at some point probably, because mixins are not supported in ES6 and React is moving away from them.

I think the only change that is needed then is that the `BaseStore` support the observable pattern.
